In [1]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\rudra\anaconda3\lib\site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog<5,>=2.1.5 in c:\users\rudra\anaconda3\lib\site-packages (from streamlit) (4.0.1)
Requirement already satisfied: jinja2 in c:\users\rudra\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\rudra\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in c:\users\rudra\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: colorama in c:\users\rudra\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\rudra\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rudra\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rudra\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rudra\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rudra\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rudra\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rudra\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rudra\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.12.14)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\rudra\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\rudra\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\rudra\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rudra\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\rudra\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\rudra\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\rudra\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\rudra\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\rudra\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in c:\users\rudra\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)

In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix

In [4]:
### lode dataset
data=pd.read_csv(r"C:\Users\rudra\LMS\Heart_Disease_Dataset.csv")
##(or) data=pd.read_csv('Heart_Disease_Dataset.csv')

In [5]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,Yes,14.96,Yes,Yes,No,7,6,Yes,Female,25-29,White,Yes,Yes,Fair,17.1,Yes,Yes,Yes
1,Yes,36.93,Yes,Yes,No,3,10,No,Female,30-34,Hispanic,"No, borderline diabetes",Yes,Poor,2.7,Yes,No,No
2,No,18.70,Yes,No,Yes,26,15,No,Male,70-74,Hispanic,No,No,Poor,15.6,Yes,Yes,Yes
3,Yes,31.43,Yes,Yes,Yes,24,20,No,Female,40-44,American Indian/Alaskan Native,"No, borderline diabetes",No,Fair,1.4,No,No,Yes
4,Yes,75.64,No,No,Yes,2,29,No,Male,35-39,White,No,Yes,Excellent,8.8,Yes,Yes,Yes

In [6]:
data.tail()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
100196,No,48.02,No,No,Yes,13,17,No,Female,45-49,White,"No, borderline diabetes",No,Fair,6.4,Yes,No,No
100197,Yes,82.88,No,No,No,29,23,No,Male,75-79,Other,"No, borderline diabetes",Yes,Very good,18.9,Yes,Yes,No
100198,No,39.46,No,Yes,Yes,23,6,Yes,Male,80 or older,Hispanic,Yes,No,Excellent,18.5,Yes,No,Yes
100199,No,46.25,Yes,Yes,Yes,9,14,No,Male,25-29,American Indian/Alaskan Native,No,No,Very good,22.7,Yes,Yes,No
100200,No,39.26,Yes,No,No,10,5,Yes,Female,25-29,Other,"No, borderline diabetes",Yes,Fair,4.1,No,No,Yes

In [7]:
data.shape

(100201, 18)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100201 entries, 0 to 100200
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      100201 non-null  object
 1   BMI               100201 non-null  float64
 2   Smoking           100201 non-null  object
 3   AlcoholDrinking   100201 non-null  object
 4   Stroke            100201 non-null  object
 5   PhysicalHealth    100201 non-null  int64
 6   MentalHealth      100201 non-null  int64
 7   DiffWalking       100201 non-null  object
 8   Sex               100201 non-null  object
 9   AgeCategory       100201 non-null  object
 10  Race              100201 non-null  object
 11  Diabetic          100201 non-null  object
 12  PhysicalActivity  100201 non-null  object
 13  GenHealth         100201 non-null  object
 14  SleepTime         100201 non-null  float64
 15  Asthma            100201 non-null  object
 16  KidneyDisease     100201 non-null  object
 17  SkinCancer        100201 non-null  object
dtypes: float64(2), int64(2), object(14)
memory usage: 13.8+ MB

In [9]:
data.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  100201.000000   100201.000000  100201.000000  100201.000000
mean       53.373302       14.503937      14.498239      12.490389
std        23.878712        8.640423       8.658639       6.632122
min        12.020000        0.000000       0.000000       1.000000
25%        32.760000        7.000000       7.000000       6.700000
50%        53.380000       14.000000      15.000000      12.500000
75%        73.950000       22.000000      22.000000      18.200000
max        94.850000       29.000000      29.000000      24.000000

In [10]:
data.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [11]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
100196    False
100197    False
100198    False
100199    False
100200    False
Length: 100201, dtype: bool

In [12]:
len(data[data.duplicated()])

0

In [13]:
data.duplicated().sum()

0

In [25]:
data=pd.get_dummies(data,columns=['Diabetic'],drop_first=True)

In [27]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy)
0,Yes,14.96,Yes,Yes,No,7,6,Yes,Female,25-29,White,Yes,Fair,17.1,Yes,Yes,Yes,False,True,False
1,Yes,36.93,Yes,Yes,No,3,10,No,Female,30-34,Hispanic,Yes,Poor,2.7,Yes,No,No,True,False,False
2,No,18.70,Yes,No,Yes,26,15,No,Male,70-74,Hispanic,No,Poor,15.6,Yes,Yes,Yes,False,False,False
3,Yes,31.43,Yes,Yes,Yes,24,20,No,Female,40-44,American Indian/Alaskan Native,No,Fair,1.4,No,No,Yes,True,False,False
4,Yes,75.64,No,No,Yes,2,29,No,Male,35-39,White,Yes,Excellent,8.8,Yes,Yes,Yes,False,False,False

In [33]:
data.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'PhysicalActivity', 'GenHealth', 'SleepTime', 'Asthma',
       'KidneyDisease', 'SkinCancer', 'Diabetic_No, borderline diabetes',
       'Diabetic_Yes', 'Diabetic_Yes (during pregnancy)'],
      dtype='object')

In [39]:
binary_columns=["Smoking","AlcoholDrinking","Stroke","DiffWalking",'PhysicalActivity',"Asthma",'KidneyDisease', 'SkinCancer']
for col in binary_columns:
    data[col]=data[col].map({'Yes':1,"No":0})

In [45]:
data=pd.get_dummies(data,columns=['Sex','AgeCategory',"Race"],drop_first=True)

In [47]:
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,PhysicalActivity,GenHealth,...,AgeCategory_60-64,AgeCategory_65-69,AgeCategory_70-74,AgeCategory_75-79,AgeCategory_80 or older,Race_Asian,Race_Black,Race_Hispanic,Race_Other,Race_White
0,Yes,14.96,1,1,0,7,6,1,1,Fair,...,False,False,False,False,False,False,False,False,False,True
1,Yes,36.93,1,1,0,3,10,0,1,Poor,...,False,False,False,False,False,False,False,True,False,False
2,No,18.70,1,0,1,26,15,0,0,Poor,...,False,False,True,False,False,False,False,True,False,False
3,Yes,31.43,1,1,1,24,20,0,0,Fair,...,False,False,False,False,False,False,False,False,False,False
4,Yes,75.64,0,0,1,2,29,0,1,Excellent,...,False,False,False,False,False,False,False,False,False,True

In [49]:
x=data.drop(columns=['HeartDisease'])
y=data['HeartDisease'].map({"Yes":1,"No":0})

In [51]:
x.head()

,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,PhysicalActivity,GenHealth,SleepTime,...,AgeCategory_60-64,AgeCategory_65-69,AgeCategory_70-74,AgeCategory_75-79,AgeCategory_80 or older,Race_Asian,Race_Black,Race_Hispanic,Race_Other,Race_White
0,14.96,1,1,0,7,6,1,1,Fair,17.1,...,False,False,False,False,False,False,False,False,False,True
1,36.93,1,1,0,3,10,0,1,Poor,2.7,...,False,False,False,False,False,False,False,True,False,False
2,18.70,1,0,1,26,15,0,0,Poor,15.6,...,False,False,True,False,False,False,False,True,False,False
3,31.43,1,1,1,24,20,0,0,Fair,1.4,...,False,False,False,False,False,False,False,False,False,False
4,75.64,0,0,1,2,29,0,1,Excellent,8.8,...,False,False,False,False,False,False,False,False,False,True